const actionTypes = {
  LOADING_START: "LOADING_START",
  LOADING_END: "LOADING_END",

  CREATE_USER_ACCOUNT_SUCCESS: "CREATE_USER_ACCOUNT_SUCCESS",
  CREATE_USER_ACCOUNT_ERROR: "CREATE_USER_ACCOUNT_ERROR",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",

  UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS",
  UPDATE_USER_INFO_ERROR: "UPDATE_USER_INFO_ERROR",

  UPDATE_NOTICATION_SETTING_SUCCESS: "UPDATE_NOTICATION_SETTING_SUCCESS",
  UPDATE_NOTICATION_SETTING_ERROR: "UPDATE_NOTICATION_SETTING_ERROR",

  GET_NOTICATION_SETTING_SUCCESS: "GET_NOTICATION_SETTING_SUCCESS",
  GET_NOTICATION_SETTING_ERROR: "GET_NOTICATION_SETTING_ERROR",

  GET_FAVOURITE_PRODUCT_SUCCESS: "GET_FAVOURITE_PRODUCT_SUCCESS",
  GET_FAVOURITE_PRODUCT_ERROR: "GET_FAVOURITE_PRODUCT_ERROR",

  ADD_TO_FAVOURITE_SUCCESS: "ADD_TO_FAVOURITE_SUCCESS",
  ADD_TO_FAVOURITE_ERROR: "ADD_TO_FAVOURITE_ERROR",
  ADD_TO_PAYMENTS_ERROR: "ADD_TO_PAYMENTS_ERROR",

  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",

  REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_ERROR: "REMOVE_FROM_CART_ERROR",

  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_ERROR: "UPDATE_CART_ERROR",

  ADD_PRODUCT_REVIEW_SUCCESS: "ADD_PRODUCT_REVIEW_SUCCESS",
  ADD_PRODUCT_REVIEW_ERROR: "ADD_PRODUCT_REVIEW_ERROR",

  GET_PRODUCT_REVIEW_SUCCESS: "GET_PRODUCT_REVIEW_SUCCESS",
  GET_PRODUCT_REVIEW_ERROR: "GET_PRODUCT_REVIEW_ERROR",

  GET_TRANSACTION_HISTORY_SUCCESS: "GET_TRANSACTION_HISTORY_SUCCESS",

  //Add Card

  ADD_PAYMENT_CARD_SUCCESS: "ADD_PAYMENT_CARD_SUCCESS",
  ADD_PAYMENT_CARD_ERROR: "ADD_PAYMENT_CARD_ERROR",

  REMOVE_PAYMENT_CARD_SUCCESS: "REMOVE_PAYMENT_CARD_SUCCESS",
  REMOVE_PAYMENT_CARD_ERROR: "REMOVE_PAYMENT_CARD_ERROR",

  CHANGE_DELIVERY_ADDRESS_SUCCESS: "CHANGE_DELIVERY_ADDRESS_SUCCESS",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export default actionTypes;
